/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/javascript_3d/scene.gltf --transform 
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-logo-3d-model-792093fab435419ab70dae39d2891cb3
Title: JavaScript Logo – 3D Model
*/

import React, { useRef } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const JavaScript = (props) => {
    const { nodes, materials } = useGLTF('/models/javascript_3d/scene-transformed.glb');
    const meshRef = useRef();

    // Subtle floating rotation on the Y-axis
    useFrame(() => {
        if (meshRef.current) {
            meshRef.current.rotation.y += 0.005;
        }
    });

    return (
        <Float floatIntensity={0.6} speed={1.5}>
            <group ref={meshRef} {...props} dispose={null}>
                <mesh geometry={nodes.Object_4.geometry} material={materials.yellow} />
                <mesh geometry={nodes.Object_5.geometry} material={materials.black} />
            </group>
        </Float>
    );
};

useGLTF.preload('/models/javascript_3d/scene-transformed.glb');
console.log('🟨 JavaScript loaded');

export default JavaScript;