/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/meeting_room/scene.gltf --transform 
Files: public/models/meeting_room/scene.gltf [644.24KB] > D:\2025-2026\SELF\threejs-portfolio\scene-transformed.glb [1.42MB] (-120%)
Author: mohitpatel4078 (https://sketchfab.com/mohitpatel4078)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shield-helicarrier-meeting-room-eff5e50ea5384118b2c33a9ba3de5727
Title: SHIELD Helicarrier Meeting Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const MeetingRoom = (props)=> {
    const { nodes, materials } = useGLTF('/models/meeting_room/scene-transformed.glb')
    return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube13_lambert14_0.geometry} material={materials.lambert14} position={[4.193, 2.017, -4.862]} rotation={[0, -0.066, 0]} scale={[0.476, 4.016, 0.795]} />
      <mesh geometry={nodes.pCylinder2_phong3_0.geometry} material={materials.phong3} position={[10.276, 3.411, -0.803]} rotation={[0, 0.087, Math.PI / 2]} scale={[0.087, 0.099, 0.087]} />
      <mesh geometry={nodes.pCylinder3_mi_metallic_paint_x1_0.geometry} material={materials.PaletteMaterial001} position={[0.235, 0.584, -5.983]} scale={0.099} />
      <mesh geometry={nodes.pCube21_lambert6_0.geometry} material={materials.lambert6} position={[1.363, 7.304, -1.717]} scale={0.193} />
      <mesh geometry={nodes.pCube24_lambert20_0.geometry} material={materials.lambert20} position={[-0.881, 3.482, -7.777]} rotation={[-0.042, -0.421, -0.095]} scale={0.099} />
      <mesh geometry={nodes.pCube25_lambert16_0.geometry} material={materials.lambert16} position={[-4.619, 0.517, -7.998]} rotation={[0.033, 0.422, -0.037]} scale={[0.17, 0.209, 0.14]} />
      <mesh geometry={nodes.pCube26_lambert17_0.geometry} material={materials.lambert17} position={[-9.156, 5.239, -8.142]} rotation={[0.025, -0.011, -1.585]} scale={[0.119, 0.147, 0.099]} />
      <mesh geometry={nodes.pCube27_lambert18_0.geometry} material={materials.lambert18} position={[-9.446, 2.55, -8.142]} rotation={[0.025, -0.011, -1.585]} scale={[0.119, 0.147, 0.099]} />
      <mesh geometry={nodes.floor_wuvsRoadKillOut_lambert2_0.geometry} material={materials.lambert2} scale={0.099} />
      <mesh geometry={nodes.background_wuvsRoadKillOut_lambert52_0.geometry} material={materials.lambert52} scale={0.099} />
      <mesh geometry={nodes.door_wuvsRoadKillOut_lambert53_0.geometry} material={materials.lambert53} position={[0, 0.116, 0]} scale={0.099} />
      <mesh geometry={nodes.walkway_wuvsRoadKillOut_lambert7_0.geometry} material={materials.lambert7} scale={0.099} />
      <mesh geometry={nodes.stairs_walkway_wuvsRoadKillOut_lambert4_0.geometry} material={materials.lambert4} scale={0.099} />
      <mesh geometry={nodes.GiantboxThing_wuvsRoadKillOut_lambert19_0.geometry} material={materials.lambert19} scale={0.099} />
      <mesh geometry={nodes.wallthing_wuvsRoadKillOut_lambert54_0.geometry} material={materials.lambert54} scale={0.099} />
      <mesh geometry={nodes.switch_wuvsRoadKillOut_lambert22_0.geometry} material={materials.lambert22} scale={0.099} />
      <mesh geometry={nodes.backpipe_wuvsRoadKillOut_lambert10_0.geometry} material={materials.lambert10} scale={0.099} />
      <mesh geometry={nodes.RoadKillOut_lambert11_0.geometry} material={materials.lambert11} position={[0, -0.943, 0]} scale={0.099} />
      <mesh geometry={nodes.RoadKillOut1_lambert12_0.geometry} material={materials.lambert12} position={[0, -2.557, 0]} scale={0.099} />
      <mesh geometry={nodes.polySurface505_lambert3_0.geometry} material={materials.lambert3} scale={0.099} />
      <mesh geometry={nodes.polySurface510_lambert5_0.geometry} material={materials.lambert5} scale={0.099} />
      <mesh geometry={nodes.polySurface778_lambert35_0.geometry} material={materials.lambert35} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface780_lambert23_0.geometry} material={materials.lambert23} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface781_blinn2_0.geometry} material={materials.blinn2} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface782_blinn3_0.geometry} material={materials.blinn3} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface783_lambert27_0.geometry} material={materials.lambert27} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface784_lambert28_0.geometry} material={materials.lambert28} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface785_lambert33_0.geometry} material={materials.lambert33} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface786_phong2_0.geometry} material={materials.phong2} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface787_lambert29_0.geometry} material={materials.lambert29} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface788_lambert30_0.geometry} material={materials.lambert30} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface789_lambert31_0.geometry} material={materials.lambert31} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface790_lambert32_0.geometry} material={materials.lambert32} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface791_lambert25_0.geometry} material={materials.lambert25} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface792_lambert26_0.geometry} material={materials.lambert26} position={[0.16, 0.145, 0.077]} rotation={[0, -1.566, 0]} scale={0.138} />
      <mesh geometry={nodes.polySurface796_lambert43_0.geometry} material={materials.lambert43} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface797_lambert38_0.geometry} material={materials.lambert38} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface798_lambert39_0.geometry} material={materials.lambert39} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface799_lambert40_0.geometry} material={materials.lambert40} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface800_lambert41_0.geometry} material={materials.lambert41} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface801_lambert49_0.geometry} material={materials.lambert49} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface802_lambert48_0.geometry} material={materials.lambert48} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface803_lambert45_0.geometry} material={materials.lambert45} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface804_lambert44_0.geometry} material={materials.lambert44} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface805_lambert51_0.geometry} material={materials.lambert51} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface806_lambert50_0.geometry} material={materials.lambert50} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface807_lambert47_0.geometry} material={materials.lambert47} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.polySurface808_lambert46_0.geometry} material={materials.lambert46} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.099} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')

export default MeetingRoom