/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/node.js_3d/scene.gltf --transform 
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nodejs-logo-3d-model-db41ca34efa54fa7b43af6d82e38abf9
Title: Node.js Logo – 3D Model
*/

import React, { useRef } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const NodeJs = (props) => {
    const { nodes, materials } = useGLTF('/models/node.js_3d/scene-transformed.glb');
    const meshRef = useRef();
    let time = 0;

    useFrame((state, delta) => {
        time += delta;
        if (meshRef.current) {
            // Gentle rotation
            meshRef.current.rotation.y -= 0.003;
            // Subtle scale pulse – relative to the base scale from props
            // We store the base scale on first frame
            if (!meshRef.current.userData.baseScale) {
                meshRef.current.userData.baseScale = props.scale || 1;
            }
            const base = meshRef.current.userData.baseScale;
            const pulse = 1 + Math.sin(time * 2) * 0.02;
            meshRef.current.scale.setScalar(base * pulse);
        }
    });

    return (
        <Float floatIntensity={0.5} speed={1.2}>
            <group ref={meshRef} {...props} dispose={null}>
                <mesh geometry={nodes.Object_4.geometry} material={materials['green.009']} />
            </group>
        </Float>
    );
};

useGLTF.preload('/models/node.js_3d/scene-transformed.glb');
console.log('🟢 Node.js loaded');

export default NodeJs;