/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/php/scene.gltf --transform 
Files: public/models/php/scene.gltf [16.86KB] > D:\2025-2026\SELF\threejs-portfolio\scene-transformed.glb [525.52KB] (-3017%)
Author: Aleksey Nemiro (https://sketchfab.com/alekseynemiro)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/elephpant-c8dc1f9a7f2443c49a1c1fc9fb1b4542
Title: elePHPant
*/

import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import React, { useRef, useState } from 'react';
import { Float, useGLTF } from '@react-three/drei';

const Php = (props) => {
    const { nodes, materials } = useGLTF('/models/php/scene-transformed.glb');
    const phpRef = useRef();
    const [hovered, setHovered] = useState(false);

    // Smooth idle animation
    useGSAP(() => {
        // Subtle floating motion (up/down and slight rotation)
        gsap.to(phpRef.current.position, {
            y: '+=0.1',
            duration: 2,
            repeat: -1,
            yoyo: true,
            ease: 'sine.inOut',
        });

        // Gentle rotation oscillation (only if not hovered)
        if (!hovered) {
            gsap.to(phpRef.current.rotation, {
                y: '+=0.2',
                duration: 3,
                repeat: -1,
                yoyo: true,
                ease: 'sine.inOut',
            });
        }
    }, [hovered]);

    // Hover effect: faster playful spin
    useGSAP(() => {
        if (hovered) {
            gsap.to(phpRef.current.rotation, {
                y: '+=6.28', // full 360° spin
                duration: 1.5,
                ease: 'power2.out',
            });
        }
    }, [hovered]);

    return (
        <Float floatIntensity={0.5} speed={2}>
            <group
                ref={phpRef}
                {...props}
                dispose={null}
                rotation={[0, Math.PI, 0]} // ✅ Fix flipping: rotate 180° to face camera
                onPointerEnter={() => setHovered(true)}
                onPointerLeave={() => setHovered(false)}
            >
                <mesh
                    geometry={nodes.Body_0.geometry}
                    material={materials.Body}
                    position={[-0.807, 2.163, -0.482]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.799}
                />
                <mesh
                    geometry={nodes.Body_1.geometry}
                    material={materials.Feet}
                    position={[-0.807, 2.163, -0.482]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.799}
                />
                <mesh
                    geometry={nodes.php_0.geometry}
                    material={materials.Text}
                    position={[-0.032, 2.278, 0.175]}
                    rotation={[0.183, Math.PI / 2, 0]}
                    scale={0.58}
                />
            </group>
        </Float>
    );
};

useGLTF.preload('/models/php/scene-transformed.glb');
console.log('🐘 PHP is loaded');

export default Php;