/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/react_logo/scene.gltf --transform
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0
Title: React logo
*/

import React, { useRef } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const ReactLogo = (props) => {
    const { nodes, materials } = useGLTF('/models/react_logo/scene-transformed.glb');
    const meshRef = useRef();

    // Gentle rotation
    useFrame(() => {
        if (meshRef.current) {
            meshRef.current.rotation.y += 0.005;
        }
    });

    return (
        <Float floatIntensity={0.6} speed={1.5}>
            <group ref={meshRef} {...props} dispose={null}>
                <mesh
                    geometry={nodes['React-Logo_Material002_0'].geometry}
                    material={materials['Material.002']}
                    position={[0, 0.079, 0.181]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={[0.392, 0.392, 0.527]}
                />
            </group>
        </Float>
    );
};

useGLTF.preload('/models/react_logo/scene-transformed.glb');
console.log('⚛️ React logo loaded');

export default ReactLogo;